version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  mongodb:
    image: mongo:latest
    ports:
        - '27017:27017'
    volumes:  
        - air_scout-mongodb:/data/db
  redis:
    image: "redis:alpine"
    ports:
        - '6379:6379'
    volumes:
        - air_scout-redis:/var/lib/redis
volumes:
    air_scout-redis:
    air_scout-mongodb: 